### ISSUE TITLE
Can be non proffesional games added?

### ISSUE THREAD

**Issue by glowiak** [skipster1337/skipster1337.github.io#4]
i mean does your site accept having on non proffesional (home developed) games?

Your site is basically the XP marketplace

**Comment by skipster1337** [comment]
Yes, any suggestions are welcome. What games would you like added?

**Comment by glowiak** [comment]
I am working on some plants vs zombies style game with very original lore but it's nothing compared to pvz

**Comment by skipster1337** [comment]
That sounds quite interesting, it would be a great addition to the list. When the game is ready, share the link and I'll make sure to add it.  
I guess I should make a separate pinned issue for software suggestions and link it on the site, so that they can all be contained on one page.

**Comment by glowiak** [comment]
The game is ready and it's like for two months on my itch.io page. Today I've released a new update and yesterday I did release two
