### ISSUE TITLE
Can you change the description for my SpotifyXP App

### ISSUE THREAD

**Issue by werwolf2303** [skipster1337/skipster1337.github.io#7]
I released a stable v1.0 and removed the clientid requirement

**Comment by skipster1337** [comment]
cool
also i checked and your client doesnt NEED premium, i have a free account and everything works lol
you might want to edit your readme to reflect that

**Comment by werwolf2303** [comment]
It doesn't work for me with a free account. So I guess its region based

**Comment by skipster1337** [comment]
oh interesting

**Comment by werwolf2303** [comment]
Can you remove the Spotify app from your list because it doesn't work anymore since dec.2022

**Comment by skipster1337** [comment]
i will keep it for archival purposes, it already has a disclaimer saying that it's broken
